Terminal/ls.terminal.ink

- src/bot.js
- src/discord/index.js
> Use widget for discord previews

- index.js
> Make ls automatically create DB & Tables

- src/dynamic/default/templates/site.pug
Please note that I have not tested this, so I am basing this off experience with Bootstrap.
> Align user related stuff on right side of navbar

- locales/en-gb.json
- locales/fr-fr.json
- locales/sv-se.json
- locales/zh-hans.json
> Describe `zh-hans` in all languages

- banner.txt
- index.js
literally having it in the code looks ugly
> Store startup banner in separate file

- README.md
> Instead of adding @ mention, I made them clickable.

- README.md
> oops, messed up iDroid's name. smh

- Dockerfile
- docker-compose.yml
So apparently people think Alpine is better in Docker, so why not use it, I have no idea why its better but whatever
> Wew Alpine

- locales/de.json
- Removing old messages.
- Adding new ones.
- Editing others.
> Updating de.json

- locales/fr.json
Updated fr.json locale : 
Corrected typos, changed some phrases to be more understandable in french, and potentially fixed https://i.imgur.com/l95DsnO.png
> Updated french translation

- locales/fr.json
Fix for https://i.imgur.com/VsKPgbb.png on bot pages
> Fixed missing translation in fr.json

- locales/fr.json
Cause I can't do everything at once
> Another fr.json update - missing texts in french

- locales/fr.json
Things keeps changing and I can't read lmfao
> Updated fr.json - missing texts again 

- locales/fr.json
> Updoot baguette.json

- locales/fr.json
do u want my ~~beguete~~ baguette?
> typo in beguete

- locales/de.json
> Error! Messages not found... Adding missing ones..

- website/README.md
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
> ADD THE VITAL PARENTHESIS MARK WHICH BURNS MY EYES

- locales/en-GB.json
also i don't know how to translate that to german or french ¯\\\_(ツ)\_/¯
> Terminal.ink did not make the bots

- locales/da.json
Not gonna make it all in one go tho but still a smol batch here anyway.
> Adding some Danish translations

- README.md
> im pretty sure depenendency is not a word - README.md

- locales/fr.json
Did you know ? In France, it is legal to marry a dead person
> Updated french translation with missing labels

- locales/pl.json
just again fixed some translations, going to fix some more as "v3" till it will be perfect :D
> polish translations "fix" v2

- locales/pl.json
fixed 1 translation as 7coil wanted :)
> Polish translations "fix" v3

- locales/fr.json
Added Youku related strings, pages.edit.discord & footer.terms
> Add missing strings
